name: 3DInfomax
channels:
  - defaults
dependencies:
  - python=3.7
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - nvidia::cudatoolkit=10.2
  - conda-forge::rdkit
  - pyg::pyg
  - pyg::pytorch-scatter
  - dglteam::dgl-cuda10.2
  - conda-forge::pot
  - conda-forge::numpy
  - conda-forge::certifi
  - conda-forge::ogb
  - conda-forge::icecream
  - conda-forge::tensorboard
